microsoft/playwright-java

.github/workflows/publish.yml

Fixing the action config in accord with https://github.com/actions/setup-java/issues/91#issuecomment-747269146

devops: update publish.yml to use env var for passphrase

---

playwright/src/main/java/com/microsoft/playwright/impl/PageImpl.java
playwright/src/test/java/com/microsoft/playwright/TestBrowserContextBasic.java

fix: correctly initialize page.isClosed()

---

playwright/src/main/java/com/microsoft/playwright/impl/Transport.java
playwright/src/test/java/com/microsoft/playwright/TestClick.java

fix: correctly encode unicode strings to UTF-8

---

playwright/src/main/java/com/microsoft/playwright/BrowserType.java
playwright/src/main/java/com/microsoft/playwright/impl/BrowserImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/BrowserTypeImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/Serialization.java
playwright/src/test/java/com/microsoft/playwright/TestBase.java
playwright/src/test/java/com/microsoft/playwright/TestBrowser.java
playwright/src/test/java/com/microsoft/playwright/TestLaunch.java
tools/api-generator/src/main/java/com/microsoft/playwright/tools/Types.java

fix: allow configuring environment variables

---

playwright/src/main/java/com/microsoft/playwright/BrowserType.java
playwright/src/test/java/com/microsoft/playwright/TestDefaultBrowserContext2.java
tools/api-generator/src/main/java/com/microsoft/playwright/tools/ApiGenerator.java
tools/api-generator/src/main/java/com/microsoft/playwright/tools/Types.java

fix: ignoreDefaultArgs and ignoreAllDefaultArgs

---

scripts/download_driver_for_all_platforms.sh

Add help section for `scripts/download_driver_for_all_platforms.sh`

chore: add help section for the driver download script

---

playwright/src/test/java/com/microsoft/playwright/TestElementHandleQuerySelector.java

test: add new test 'Element Handle Query Selector'

---

playwright/src/test/java/com/microsoft/playwright/TestElementHandlePress.java
playwright/src/test/java/com/microsoft/playwright/TestElementHandleType.java

add new test 'Element Handle Type' and 'Element Handle Press'

test: add new test 'Element Handle Type' and 'Element Handle Press'

---

playwright/src/test/java/com/microsoft/playwright/TestPageKeyboard.java

test: add new test 'Page Keyboard'

---

playwright/src/test/java/com/microsoft/playwright/TestSelectorsCss.java

test: add new test 'Selectors CSS'

---

playwright/src/main/java/com/microsoft/playwright/Playwright.java
playwright/src/main/java/com/microsoft/playwright/impl/PlaywrightImpl.java
tools/api-generator/src/main/java/com/microsoft/playwright/tools/ApiGenerator.java

fix: remove Exception from Playwright.close signature

---

playwright/src/main/java/com/microsoft/playwright/BrowserType.java
tools/api-generator/src/main/java/com/microsoft/playwright/tools/ApiGenerator.java

fix: allow building persistent context options from device

---

playwright/src/main/java/com/microsoft/playwright/impl/LoggingSupport.java

fix(logging): use thread-safe time formatter

---

playwright/src/test/java/com/microsoft/playwright/TestNetworkPostData.java

tests: port new postData tests from upstream

---

.github/workflows/test.yml
driver-bundle/src/main/java/com/microsoft/playwright/impl/DriverJar.java
playwright/src/test/java/com/microsoft/playwright/TestBrowserTypeConnect.java
scripts/set_maven_version.sh
tools/test-spring-boot-starter/pom.xml
tools/test-spring-boot-starter/src/main/java/com/microsoft/playwright/springboottest/TestApp.java

fix: supported driver jar packed into another jar

---

playwright/src/main/java/com/microsoft/playwright/impl/Serialization.java
playwright/src/test/java/com/microsoft/playwright/TestBase.java
playwright/src/test/java/com/microsoft/playwright/TestFirefoxLauncher.java
playwright/src/test/java/com/microsoft/playwright/Utils.java

fix(launcher): firefoxUserPrefs serialization

---

Dockerfile.focal

fix(docker): set java home, use JDK 14

---

.github/workflows/publish_canary_docker.yml
.github/workflows/test_docker.yml
scripts/tag_image_and_push.sh

devops: publish docker canary

---

playwright/src/test/java/com/microsoft/playwright/TestBrowserContextLocale.java

test(lolcale): port locale tests from typescript

---

playwright/src/main/java/com/microsoft/playwright/impl/WebSocketTransport.java

fix(websocket): use incoming queue with unlimited capacity

---

playwright/src/test/java/com/microsoft/playwright/TestBrowserContextCookies.java

test: check that SameSiteAttribute is properly propagated

---

playwright/src/main/java/com/microsoft/playwright/impl/BrowserContextImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/ChannelOwner.java
playwright/src/main/java/com/microsoft/playwright/impl/PageImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/Utils.java
playwright/src/main/java/com/microsoft/playwright/impl/WaitForEventLogger.java
playwright/src/main/java/com/microsoft/playwright/impl/WebSocketImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/WorkerImpl.java

https://github.com/microsoft/playwright/issues/6223

feat(inspector): add logging to wait for event methods

---

playwright/src/main/java/com/microsoft/playwright/impl/Connection.java

feat: support channel logging

---

playwright/src/main/java/com/microsoft/playwright/impl/BrowserTypeImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/Utils.java
playwright/src/main/java/com/microsoft/playwright/impl/WebSocketTransport.java
playwright/src/test/java/com/microsoft/playwright/TestBrowserTypeConnect.java

fix: support slowMo options in browserType.connect

---

playwright/src/test/java/com/microsoft/playwright/TestBrowserTypeConnect.java

test: port more browserType.connect() tests

---

playwright/src/main/java/com/microsoft/playwright/impl/WebSocketImpl.java
playwright/src/test/java/com/microsoft/playwright/TestWebSocket.java

fix: respect WebSocket.waitForFrame* predicate

---

playwright/src/main/java/com/microsoft/playwright/impl/WebSocketImpl.java
playwright/src/test/java/com/microsoft/playwright/TestWebSocket.java

Master branch commit: https://github.com/microsoft/playwright-java/commit/1958a2fa64adecdc6be9a0605571b9dfc332085b
#487

cherry-pick(1.12): fix: respect WebSocket.waitForFrame* predicate (#490)

---

playwright/src/main/java/com/microsoft/playwright/impl/TracingImpl.java
playwright/src/test/java/com/microsoft/playwright/TestBrowserTypeConnect.java
playwright/src/test/java/com/microsoft/playwright/TestChromium.java

fix: support tracing over CDP

---

playwright/src/main/java/com/microsoft/playwright/impl/TracingImpl.java
playwright/src/test/java/com/microsoft/playwright/TestBrowserTypeConnect.java
playwright/src/test/java/com/microsoft/playwright/TestChromium.java

Master branch commit: https://github.com/microsoft/playwright-java/commit/539b18f167d05d1153e4b6c17b99591d49c44490
Bug:  #489

cherry-pick(1.12): fix: support tracing over CDP (#492)

---

playwright/src/main/java/com/microsoft/playwright/impl/ElementHandleImpl.java
playwright/src/test/java/com/microsoft/playwright/TestElementHandleMisc.java

fix: NPE in ElementHandle.hover()

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/question.yml

Downstream sync for https://github.com/microsoft/playwright/pull/7477

chore: sync with upstream GitHub issue templates

---

playwright/src/main/java/com/microsoft/playwright/impl/Router.java
playwright/src/test/java/com/microsoft/playwright/TestBrowserContextRoute.java
playwright/src/test/java/com/microsoft/playwright/TestPageRoute.java

This PR mirrors https://github.com/microsoft/playwright/pull/7585
https://github.com/microsoft/playwright/issues/7394

fix: reverse route handlers order

---

playwright/src/main/java/com/microsoft/playwright/impl/WebSocketImpl.java
playwright/src/test/java/com/microsoft/playwright/TestWebSocket.java

Ports https://github.com/microsoft/playwright/pull/7360 to Java

fix(websockets): filter for text and binary frames

---

driver-bundle/src/main/java/com/microsoft/playwright/impl/DriverJar.java

fix: do not download browsers if PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1

---

.github/workflows/verify_api.yml
README.md
scripts/update_readme.sh

devops: check that browser versions in README are up to date

---

.github/workflows/publish.yml

https://github.com/microsoft/playwright-java/commit/29c0df6443666d9534121428255a5e9a4d7143a4

cherry-pick(release-1.14): fix publish workflow (#565)

---

playwright/src/main/java/com/microsoft/playwright/Browser.java
playwright/src/main/java/com/microsoft/playwright/BrowserContext.java
playwright/src/main/java/com/microsoft/playwright/BrowserType.java
playwright/src/main/java/com/microsoft/playwright/ConsoleMessage.java
playwright/src/main/java/com/microsoft/playwright/Page.java
tools/api-generator/src/main/java/com/microsoft/playwright/tools/ApiGenerator.java

docs: fix @link reference for method with alias

---

ROLLING.md

This docs describes how to roll to the Playwright driver.

docs: add rolling.md

---

playwright/src/main/java/com/microsoft/playwright/Browser.java
playwright/src/main/java/com/microsoft/playwright/BrowserContext.java
playwright/src/main/java/com/microsoft/playwright/BrowserType.java
playwright/src/main/java/com/microsoft/playwright/ElementHandle.java
playwright/src/main/java/com/microsoft/playwright/FileChooser.java
playwright/src/main/java/com/microsoft/playwright/Frame.java
playwright/src/main/java/com/microsoft/playwright/Keyboard.java
playwright/src/main/java/com/microsoft/playwright/Locator.java
playwright/src/main/java/com/microsoft/playwright/Mouse.java
playwright/src/main/java/com/microsoft/playwright/Page.java
playwright/src/main/java/com/microsoft/playwright/Playwright.java
playwright/src/main/java/com/microsoft/playwright/Route.java
playwright/src/main/java/com/microsoft/playwright/Selectors.java
playwright/src/main/java/com/microsoft/playwright/Tracing.java
playwright/src/main/java/com/microsoft/playwright/WebSocket.java
playwright/src/main/java/com/microsoft/playwright/Worker.java
playwright/src/main/java/com/microsoft/playwright/options/Cookie.java
playwright/src/main/java/com/microsoft/playwright/options/Geolocation.java
playwright/src/main/java/com/microsoft/playwright/options/Margin.java
playwright/src/main/java/com/microsoft/playwright/options/Proxy.java
playwright/src/main/java/com/microsoft/playwright/options/SelectOption.java
tools/api-generator/src/main/java/com/microsoft/playwright/tools/ApiGenerator.java

docs: duplicate field docs to builder methods

---

playwright/src/main/java/com/microsoft/playwright/impl/BrowserContextImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/PageImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/WebSocketImpl.java
playwright/src/test/java/com/microsoft/playwright/TestPageEventConsole.java

fix: respect predicate in waitFor* methods

---

playwright/src/test/java/com/microsoft/playwright/TestPageNetworkSizes.java

Fixes https://github.com/microsoft/playwright-java/issues/610

test: fix sizes test by using no chunked requests

---

scripts/set_maven_version.sh

https://stackoverflow.com/questions/15978218/how-to-update-the-maven-version-without-pom-backup-files

chore(set_maven_version): do not generate version backups

---

driver-bundle/src/main/java/com/microsoft/playwright/impl/DriverJar.java
driver-bundle/src/test/java/com/microsoft/playwright/TestInstall.java
playwright/src/main/java/com/microsoft/playwright/impl/BrowserContextImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/PlaywrightImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/Serialization.java
playwright/src/main/java/com/microsoft/playwright/impl/Utils.java
scripts/install_local_driver.sh

Hi, I got a problem when try to download the driver by `install_local_driver.sh`, I found that the download url is incorrect, and it resulted in download failure finally, so I try to read its code and fixed this issue, referred to the `download_driver_for_all_platforms.sh`. It works now, I have a test on my macOS machine.

fix(scripts): install_local_driver.sh can't download driver successfully

---

.github/workflows/test.yml

https://github.com/microsoft/playwright-java/issues/737

devops: run tests on Java 17

---

playwright/pom.xml
pom.xml

feat: inclide Implementation-Version into manifest

---

.github/workflows/test_cli.yml
playwright/src/main/java/com/microsoft/playwright/CLI.java
tools/test-cli-version/pom.xml
tools/test-cli-version/src/main/java/com/microsoft/playwright/testcliversion/TestApp.java
tools/test-cli-version/test.sh
tools/test-local-installation/src/README.md

feat: make --version return java package version

---

playwright/src/test/java/com/microsoft/playwright/TestPageRoute.java

test: unroute predicate

---

playwright/src/main/java/com/microsoft/playwright/impl/TracingImpl.java

https://github.com/microsoft/playwright-java/commit/897d441c02fecb80ef385faf8f4d72c4153baaeb

cherry-pick(1.18): include var name into tracing error message (#779)

---

playwright/src/main/java/com/microsoft/playwright/impl/RouteImpl.java
playwright/src/test/java/com/microsoft/playwright/TestRequestFulfill.java

fix: throw if route is handled twice

---

playwright/src/main/java/com/microsoft/playwright/impl/Utils.java

fix: skip synthetic fields when converting options

---

playwright/src/main/java/com/microsoft/playwright/impl/AssertionsBase.java
playwright/src/test/java/com/microsoft/playwright/TestLocatorAssertions.java
playwright/src/test/java/com/microsoft/playwright/TestPageAssertions.java

fix(assertions): include expected/actual values into error message

---

playwright/src/main/java/com/microsoft/playwright/impl/Connection.java
playwright/src/main/java/com/microsoft/playwright/impl/StackTraceCollector.java
playwright/src/test/java/com/microsoft/playwright/TestTracing.java

fix: support multiple source dirs

---

.github/workflows/publish_canary_docker.yml
.github/workflows/publish_docker_release.yml
.github/workflows/test_docker.yml
scripts/tag_image_and_push.sh
utils/docker/Dockerfile.focal
utils/docker/README.md
utils/docker/build.sh
utils/docker/publish_docker.sh

This aligns the build infra with the upstream infra which we use now across all the language bindings.
As a drive by, we get:
- arm images
- pwuser support
- easier maintenance

chore: align Docker with upstream Docker infra

---

playwright/src/main/java/com/microsoft/playwright/impl/BrowserTypeImpl.java
playwright/src/test/java/com/microsoft/playwright/TestBrowserTypeConnect.java

fix: send x-playwright-browser

---

playwright/src/main/java/com/microsoft/playwright/impl/LocatorAssertionsImpl.java
playwright/src/test/java/com/microsoft/playwright/TestLocatorAssertions.java

fix: respect isChecked options

---

.github/workflows/trigger_internal_tests.yml

devops: add workflow triggering internal tests

---

README.md

docs: update docs link

---

playwright/src/main/java/com/microsoft/playwright/impl/BrowserContextImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/PageImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/RouteImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/Router.java
playwright/src/test/java/com/microsoft/playwright/TestBrowserContextRoute.java
playwright/src/test/java/com/microsoft/playwright/TestPageRoute.java

Corresponding upstream change: https://github.com/microsoft/playwright/pull/14771

feat: route chaining

---

playwright/src/test/java/com/microsoft/playwright/TestPageNetworkRequest.java

test: 403 response still has postBody

---

playwright/src/main/java/com/microsoft/playwright/impl/BrowserTypeImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/Connection.java
playwright/src/main/java/com/microsoft/playwright/impl/PlaywrightImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/StackTraceCollector.java
playwright/src/test/java/com/microsoft/playwright/TestBase.java
playwright/src/test/java/com/microsoft/playwright/TestJavaSourceLocationInConstructor.java

feat: accept PLAYWRIGHT_JAVA_SRC in Playwright.create

---

utils/docker/Dockerfile.focal

https://github.com/microsoft/playwright-dotnet/issues/2223

chore: add 'gpg' package to Docker images

---

playwright/src/main/java/com/microsoft/playwright/impl/Serialization.java
playwright/src/test/java/com/microsoft/playwright/TestPageLocatorQuery.java

fix: do not escape html symbols when serializing strings to json

---

driver-bundle/src/main/java/com/microsoft/playwright/impl/DriverJar.java

fix: do not download browsers if selenium url is set

---

playwright/src/test/java/com/microsoft/playwright/TestLocatorMisc.java

test: locator has with unicode symbols

---

driver-bundle/src/main/java/com/microsoft/playwright/impl/driver/jar/DriverJar.java
driver-bundle/src/test/java/com/microsoft/playwright/impl/driver/jar/TestInstall.java
driver/src/main/java/com/microsoft/playwright/impl/driver/Driver.java
playwright/src/main/java/com/microsoft/playwright/CLI.java
playwright/src/main/java/com/microsoft/playwright/impl/PlaywrightImpl.java
playwright/src/test/java/com/microsoft/playwright/TestBrowserTypeConnect.java
playwright/src/test/java/com/microsoft/playwright/TestPlaywrightCreate.java

This PR depends on https://github.com/microsoft/playwright/pull/16518
https://github.com/microsoft/playwright-java/issues/1016

feat: allow using preinstalled node.js

---

playwright/src/main/java/com/microsoft/playwright/impl/BrowserContextImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/ChannelOwner.java
playwright/src/main/java/com/microsoft/playwright/impl/FrameImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/HARRouter.java
playwright/src/main/java/com/microsoft/playwright/impl/Logger.java
playwright/src/main/java/com/microsoft/playwright/impl/LoggingSupport.java
playwright/src/main/java/com/microsoft/playwright/impl/PageImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/UrlMatcher.java
playwright/src/main/java/com/microsoft/playwright/impl/WaitForEventLogger.java
playwright/src/main/java/com/microsoft/playwright/impl/WebSocketImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/WorkerImpl.java

Fixes https://github.com/microsoft/playwright-java/issues/825

fix: log url for waitFor* methods

---

playwright/src/main/java/com/microsoft/playwright/impl/Router.java
playwright/src/test/java/com/microsoft/playwright/TestPageRequestFallback.java

An attempt to fix:
```
org.opentest4j.AssertionFailedError: expected: <fulfilled one> but was: <>
at com.microsoft.playwright.TestPageRequestFallback.shouldChainOnce(TestPageRequestFallback.java:137)
```
on Windows WebKit.

fix: unflake TestPageRequestFallback.shouldChainOnce on win

---

README.md

Added example in README.md to add Playwright dependency in build.gradle

Added example in README.md for Gradle project

---

playwright/src/main/java/com/microsoft/playwright/impl/LocatorImpl.java
playwright/src/test/java/com/microsoft/playwright/TestSelectorsGetBy.java

https://github.com/microsoft/playwright-java/issues/1130

fix: implement LocatorImpl.getByRole

---

playwright/src/main/java/com/microsoft/playwright/impl/Serialization.java
playwright/src/test/java/com/microsoft/playwright/TestBrowserContextFetch.java

Fixes https://github.com/microsoft/playwright-java/issues/1141

fix: Date and LocalDateTime serialization in post data

---

pom.xml

https://github.com/microsoft/playwright-java/issues/1149

chore(tests): suppress surefire plugin "Corrupted STDOUT..." warning

---

.azure-pipelines/publish.yml

devops: add azure pipeline for release publishing

---

playwright/src/main/java/com/microsoft/playwright/impl/LocatorUtils.java
playwright/src/test/java/com/microsoft/playwright/TestSelectorsGetBy.java

https://github.com/microsoft/playwright/issues/20471

fix: properly escape slash inside attributes

---

pom.xml

fix: Improve maven plugin configuration

---

playwright/src/test/java/com/microsoft/playwright/TestPageWaitForNavigation.java
playwright/src/test/java/com/microsoft/playwright/TestPageWaitForUrl.java

Related node.js change: https://github.com/microsoft/playwright/pull/20042

test: make waitForNavigation pass in ff

---

playwright/src/main/java/com/microsoft/playwright/impl/LocatorAssertionsImpl.java
playwright/src/test/java/com/microsoft/playwright/TestCheck.java
playwright/src/test/java/com/microsoft/playwright/TestLocatorAssertions.java

fix: better assertThat error message for isChecked=false

---

playwright/src/main/java/com/microsoft/playwright/impl/APIRequestContextImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/Utils.java
playwright/src/test/java/com/microsoft/playwright/TestGlobalFetch.java

fix: do not modify fetch options.method

---

playwright/src/main/java/com/microsoft/playwright/impl/BrowserContextImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/PageImpl.java
playwright/src/test/java/com/microsoft/playwright/TestBrowserTypeConnect.java

This is a backport of https://github.com/microsoft/playwright/commit/09ff7eaaf2ab40fcaf0abb85f0308a91e1460a97

chore: throw on context.close() if it was closed externally

---

playwright/src/test/java/com/microsoft/playwright/TestPageWaitForNavigation.java

Align with recent changes https://github.com/microsoft/playwright/pull/21542

test: align waitForNavigation test with upstream

---

playwright/src/main/java/com/microsoft/playwright/impl/BrowserContextImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/PageImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/TimeoutSettings.java

fix: NPE after pause

---

playwright/src/main/java/com/microsoft/playwright/impl/BrowserContextImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/PageImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/TimeoutSettings.java

Cherry-pick d219fddc8b6942b77bf443259c200bd378af0126
https://github.com/microsoft/playwright-java/issues/1313

cherry-pick(#1314): fix: NPE after pause

---

playwright/src/main/java/com/microsoft/playwright/impl/Serialization.java
playwright/src/test/java/com/microsoft/playwright/TestBrowserContextFetch.java
playwright/src/test/java/com/microsoft/playwright/TestPageSetExtraHttpHeaders.java

fix: form data field encoding

---

playwright/src/main/java/com/microsoft/playwright/impl/Utils.java

Resolves #1381
@yury-s here is a fix for the OOM exception when uploading large or many files.
Notes:
First used `Math.addExact()` for the calculation, then found it a bit of a overkill and reverted it.
Thx for your review and feedback!

fix: setfiles OOM exception

---

playwright/src/test/java/com/microsoft/playwright/TestBrowserContextAddCookies.java

Fixes 
This is similar to node.js https://github.com/microsoft/playwright/pull/19459

test: unflake cookie roundtrip

---

utils/docker/Dockerfile.focal
utils/docker/Dockerfile.jammy

chore: bump maven version

---

playwright/src/main/java/com/microsoft/playwright/junit/Options.java
playwright/src/main/java/com/microsoft/playwright/junit/OptionsFactory.java
playwright/src/main/java/com/microsoft/playwright/junit/UsePlaywright.java
playwright/src/main/java/com/microsoft/playwright/junit/impl/BrowserExtension.java
playwright/src/main/java/com/microsoft/playwright/junit/impl/DefaultOptions.java
playwright/src/main/java/com/microsoft/playwright/junit/impl/OptionsExtension.java
playwright/src/test/java/com/microsoft/playwright/FixtureTest.java
playwright/src/test/java/com/microsoft/playwright/ServerLifecycle.java
playwright/src/test/java/com/microsoft/playwright/TestPlaywrightCustomFixtures.java
playwright/src/test/java/com/microsoft/playwright/TestPlaywrightCustomOptionFixtures.java

@yury-s I added some tests because i found a bug in the options.  Also removed all setters as they don't seem useful (correct me if i'm wrong)

Remove setters from Options.  Add tests for custom fixtures

---

playwright/src/main/java/com/microsoft/playwright/impl/ElementHandleImpl.java
playwright/src/test/java/com/microsoft/playwright/TestPageSetInputFiles.java

Fixes https://github.com/microsoft/playwright-java/issues/1468

fix: put file payloads into "payloads" protocol field

---

.azure-pipelines/publish.yml

Doing the same as in https://github.com/microsoft/playwright-browsers/compare/a2078c881d89ae334ee6609b86e39f48c1cd653c...c4b851fa133aaf6097cd4d6fa3c7e7bbb53bf800.

devops: migrate to 1ES PT

---

playwright/src/test/java/com/microsoft/playwright/Server.java
playwright/src/test/java/com/microsoft/playwright/Utils.java
playwright/src/test/java/com/microsoft/playwright/junit/FixtureTest.java
playwright/src/test/java/com/microsoft/playwright/junit/ServerLifecycle.java
playwright/src/test/java/com/microsoft/playwright/junit/TestFixtureChannelOption.java
playwright/src/test/java/com/microsoft/playwright/junit/TestFixtureContextOptions.java
playwright/src/test/java/com/microsoft/playwright/junit/TestFixtureDeviceOption.java
playwright/src/test/java/com/microsoft/playwright/junit/TestFixtureOptions.java
playwright/src/test/java/com/microsoft/playwright/junit/TestFixtures.java

chore: move junit tests into junit package

---

.github/workflows/test.yml
CONTRIBUTING.md
examples/pom.xml
pom.xml
tools/api-generator/pom.xml
tools/test-cli-fatjar/pom.xml
tools/test-cli-version/pom.xml
tools/test-local-installation/pom.xml
tools/update-docs-version/pom.xml

Resolves https://github.com/microsoft/playwright-java/pull/1483

chore: bump dependencies

---

.github/dependabot.yml

Related https://github.com/microsoft/playwright-java/pull/1484

devops: add maven dependabot

---

playwright/src/main/java/com/microsoft/playwright/junit/Options.java
playwright/src/main/java/com/microsoft/playwright/junit/impl/BrowserContextExtension.java
playwright/src/test/java/com/microsoft/playwright/junit/TestFixtureContextOptions.java

Fix typo : `contextOption` to `contextOptions`
Remove storageStatePath and viewportSize as per discussion https://github.com/microsoft/playwright-java/issues/1369#issuecomment-1924579887

JUnit minor fixes

---

playwright/src/main/java/com/microsoft/playwright/junit/Options.java
playwright/src/main/java/com/microsoft/playwright/junit/impl/APIRequestContextExtension.java
playwright/src/main/java/com/microsoft/playwright/junit/impl/BrowserContextExtension.java
playwright/src/main/java/com/microsoft/playwright/junit/impl/BrowserExtension.java

Following https://github.com/microsoft/playwright-java/issues/1369#issuecomment-1924579887
I don't have a strong opinion on letting the fields public or set them private. So this PR can be discussed, or even dropped.

remove JUnit Options getters

---

utils/docker/Dockerfile.focal
utils/docker/Dockerfile.jammy

Fixes https://github.com/microsoft/playwright-java/issues/1417

chore: use latest JDK LTS version in docker

---

playwright/src/main/java/com/microsoft/playwright/impl/SelectorsImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/SharedSelectors.java
playwright/src/test/java/com/microsoft/playwright/TestSelectorsGetBy.java

chore: send testIdAttributeName to server

---

playwright/src/main/java/com/microsoft/playwright/junit/Options.java
playwright/src/main/java/com/microsoft/playwright/junit/impl/BrowserContextExtension.java
playwright/src/main/java/com/microsoft/playwright/junit/impl/BrowserExtension.java
playwright/src/main/java/com/microsoft/playwright/junit/impl/ExtensionUtils.java
playwright/src/main/java/com/microsoft/playwright/junit/impl/PlaywrightExtension.java
playwright/src/test/java/com/microsoft/playwright/junit/TestFixtureOptions.java

feat(junit): testIdAttribute option

---

playwright/src/main/java/com/microsoft/playwright/junit/Options.java
playwright/src/main/java/com/microsoft/playwright/junit/impl/PlaywrightExtension.java

I forgot one getter...
Following https://github.com/microsoft/playwright-java/pull/1487

fix: remove remaining JUnit Option getter

---

playwright/src/main/java/com/microsoft/playwright/junit/impl/PlaywrightExtension.java

Reference: https://github.com/microsoft/playwright-java/issues/1369#issuecomment-1924579887

chore: track Playwright instances in PlaywrightRegistry

---

playwright/src/main/java/com/microsoft/playwright/junit/Options.java
playwright/src/main/java/com/microsoft/playwright/junit/OptionsFactory.java
playwright/src/main/java/com/microsoft/playwright/junit/UsePlaywright.java

docs: junit fixture javadocs

---

driver-bundle/src/main/java/com/microsoft/playwright/impl/driver/jar/DriverJar.java
driver-bundle/src/test/java/com/microsoft/playwright/impl/driver/jar/TestInstall.java
driver/src/main/java/com/microsoft/playwright/impl/driver/Driver.java
playwright/src/test/java/com/microsoft/playwright/TestBrowserTypeConnect.java

Fixes https://github.com/microsoft/playwright-java/issues/1518

chore: get rid of driver wrapper script

---

playwright/src/test/java/com/microsoft/playwright/TestAPIResponseAssertions.java
playwright/src/test/java/com/microsoft/playwright/TestAssertThatIsInViewport.java
playwright/src/test/java/com/microsoft/playwright/TestBeforeunload.java
playwright/src/test/java/com/microsoft/playwright/TestBrowserContextAddCookies.java
playwright/src/test/java/com/microsoft/playwright/TestBrowserContextBaseUrl.java
playwright/src/test/java/com/microsoft/playwright/TestBrowserContextBasic.java
playwright/src/test/java/com/microsoft/playwright/TestOptionsFactories.java

@yury-s, converted more tests to use fixtures

chore(test): Convert tests to use fixtures

---

playwright/src/main/java/com/microsoft/playwright/junit/impl/APIRequestContextExtension.java
playwright/src/main/java/com/microsoft/playwright/junit/impl/BrowserContextExtension.java
playwright/src/main/java/com/microsoft/playwright/junit/impl/BrowserExtension.java
playwright/src/main/java/com/microsoft/playwright/junit/impl/PageExtension.java
playwright/src/main/java/com/microsoft/playwright/junit/impl/PlaywrightExtension.java

feat(junit): make getOrCreate fixture methods public

---

playwright/pom.xml
pom.xml

Reference https://github.com/microsoft/playwright-java/issues/1533

cherry-pick(#1534): fix(docs): generate javadocs

---

driver/src/main/java/com/microsoft/playwright/impl/driver/Driver.java

Fixes https://github.com/microsoft/playwright-java/issues/1548

fix(driver): consider PLAYWRIGHT_NODEJS_PATH from host env

---

playwright/src/main/java/com/microsoft/playwright/impl/CDPSessionImpl.java

Following our protocol spec: https://github.com/microsoft/playwright/blob/82aefd24db1ba9977c3f6953347ee266845790ea/packages/protocol/src/protocol.yml#L3110

fix(cdpSession): events without payload

---

.github/workflows/publish_docker.yml

https://github.com/microsoft/playwright-internal/issues/203

devops: migrate to OIDC for Docker publishing

---

playwright/src/main/java/com/microsoft/playwright/impl/PageImpl.java
playwright/src/test/java/com/microsoft/playwright/TestPageKeyboard.java
pom.xml

Drive-by: remove expired location handler from local map.
Reference https://github.com/microsoft/playwright-java/issues/1529

test: ControlOrMeta modifier

---

playwright/src/main/java/com/microsoft/playwright/impl/APIRequestContextImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/Serialization.java
playwright/src/test/java/com/microsoft/playwright/TestBrowserContextFetch.java

Fixes https://github.com/microsoft/playwright-java/issues/1585

fix(fetch): support json objects with null values

---

playwright/src/main/java/com/microsoft/playwright/impl/Serialization.java
playwright/src/test/java/com/microsoft/playwright/TestBrowserContextFetch.java

Fixes https://github.com/microsoft/playwright-java/issues/1623

feat: support java.time.OffsetDateTime in post data

---

README.md

follow up to https://github.com/microsoft/playwright/pull/32020

docs: add discord link in readme

---

playwright/src/main/java/com/microsoft/playwright/impl/Serialization.java
playwright/src/test/java/com/microsoft/playwright/TestLocatorClick.java

Fixes: https://github.com/microsoft/playwright-java/issues/1643

fix: support ControlOrMeta action modifier

---

scripts/download_driver.sh
utils/docker/Dockerfile.focal
utils/docker/Dockerfile.jammy
utils/docker/Dockerfile.noble

Fixes https://github.com/microsoft/playwright-java/issues/1678

devops: use wget for driver downloads

---

examples/pom.xml
scripts/roll_driver.sh
scripts/set_maven_version.sh

Fixes https://github.com/microsoft/playwright-java/issues/1736

chore: auto update example pw version in pom

---

.azure-pipelines/publish.yml

Similar to https://github.com/microsoft/playwright-browsers/pull/1524.

devops: use PME environment for ESRP publishing

---

CodeQL.yml

See: https://codeql.microsoft.com/issues/5f3163c8-6b9c-48bf-8639-7fd0623f5937?copilot_promptid=E91B0CE9-0C1B-4AC2-8A46-33F49B67E058

devops: ignore tests in CodeQL checks
