microsoft/playwright-java

Dockerfile.focal

The file is based on https://github.com/microsoft/playwright/blob/master/docs/docker/Dockerfile.focal and replaces node dependencies with JDK and Maven.

devops: add basic Dockerfile

---

playwright/pom.xml

Having `<source>8</source>` in the javadoc plugin config results in very bizarre behavior. It wouldn't respect excludePackageNames tag, or even crash with assertion failure. Also excludePackageNames only works in conjunction with subpackages.

fix: skip javadoc generation for .impl package

---

CONTRIBUTING.md

1. Problem one
[Detail] docs(CONTRIBUTING.md): correct the filename of playwright-cli binary download script. It should be 'scripts/install_local_driver.sh' now instead of 'scripts/download_driver.sh'.
2. Problem two
[Detail] fix: an error 'No such file or directory' occurred when execute ./install_local_driver.sh. The detail error is './install_local_driver.sh: line 12: cd: ../driver/src/main/resources: No such file or directory', and its reason is that there is no 'resources' directory in the module 'driver', just create it and problem solved.

docs: correct a document error and Fix an error about executing ./install_local_driver.sh

---

examples/pom.xml

It avoid the following warning:
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!

chore: set example encoding to utf-8

---

driver-bundle/src/main/java/com/microsoft/playwright/impl/DriverJar.java
driver/src/main/java/com/microsoft/playwright/impl/Driver.java

Hi, I find an exception message which make me a little confused, so I try to improve it. Here are the details:
I meet the exception `java.lang.RuntimeException: Failed to find playwright-cli` when run `mvn test`, and another exception followed by this exception is `java.lang.RuntimeException: Timed out waiting for browsers to install`, just like this:
But the truth is that `playwright-cli` has already exists, the real exception is due to timeout waiting for browser to install.
Maybe it could be improved here and make it easily understood. We can give the exception and message `Failed to find playwright-cli` just only where it could happen, and as for the place where this exception message was given before, we can give the exception message like `Failed to create driver`, just like this …

chore: give more friendly exception info while create driver

---

playwright/src/main/java/com/microsoft/playwright/Page.java
playwright/src/test/java/com/microsoft/playwright/TestPdf.java
tools/api-generator/src/main/java/com/microsoft/playwright/tools/Types.java

fix(pdf): change type of pdf scale option to double

---

Dockerfile.focal

Fix issue #190 
Hi, there is indeed a minor issue. Now the script file should be `./scripts/download_driver_for_all_platforms.sh`.

fix(scripts): Dockerfile is outdated

---

playwright/src/main/java/com/microsoft/playwright/impl/AccessibilityImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/BrowserContextImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/BrowserImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/BrowserTypeImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/ChannelOwner.java
playwright/src/main/java/com/microsoft/playwright/impl/Connection.java
playwright/src/main/java/com/microsoft/playwright/impl/DialogImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/DownloadImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/ElementHandleImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/FileChooserImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/FrameImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/JSHandleImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/KeyboardImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/LoggingSupport.java
playwright/src/main/java/com/microsoft/playwright/impl/MouseImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/PageImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/RequestImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/ResponseImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/RouteImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/SelectorsImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/TouchscreenImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/WebSocketImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/WorkerImpl.java

Methods that go to the backend over rpc are wrapped into logging scopes. This somewhat bloats the implementation classes but still feels better than wrapping each public class into a logging decorator (tried that in https://github.com/yury-s/playwright-java/tree/generate-logging-wrappers and it seemed more verbose and harder to maintain).

feat(logging): support DEBUG=pw:api

---

playwright/src/main/java/com/microsoft/playwright/impl/DialogImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/PageImpl.java
playwright/src/test/java/com/microsoft/playwright/TestPageBasic.java

This should fix flakiness in `TestPageBasic.shouldRunBeforeunloadIfAskedFor` (see [this run](https://github.com/microsoft/playwright-java/pull/196/checks?check_run_id=1663558029) for example).

fix: do not dismiss dialogs automatically

---

scripts/generate_api.sh

Got a prompt message like this `playwright-java/driver-bundle/src/main/resources/driver/linux/node: cannot execute binary file` when I was executing `./scripts/generate_api.sh` on my `macOS Big Sur 11.1`, guess that is caused by different platform, so maybe we need to consider distinguishing the path of `playwright.sh` by platform.

fix(scripts): 'generate_api.sh' does not work on macOS

---

playwright/src/main/java/com/microsoft/playwright/impl/JSHandleImpl.java
playwright/src/test/java/com/microsoft/playwright/TestElementHandleConvenience.java

* Also implemented `JSHandle.toString()` that returns preview same as upstream.

test(dom): convert remaining element handle convenience tests

---

playwright/src/main/java/com/microsoft/playwright/Dialog.java
playwright/src/main/java/com/microsoft/playwright/impl/DialogImpl.java
playwright/src/test/java/com/microsoft/playwright/TestDialog.java
playwright/src/test/java/com/microsoft/playwright/TestPageBasic.java
tools/api-generator/src/main/java/com/microsoft/playwright/tools/ApiGenerator.java
tools/api-generator/src/main/java/com/microsoft/playwright/tools/Types.java

Unifying this with upstream. String allows to add new dialog types in the future should they emerge.

fix(api): make Dialog.type() return string

---

playwright/src/main/java/com/microsoft/playwright/impl/BrowserContextImpl.java
playwright/src/test/java/com/microsoft/playwright/TestBrowserContextStorageState.java

When the path chosen to write the storage state is a relative path to the current directory (such as `Paths.get("state.json")`), the code tried to create directories for the parent path, which is null, thus causing a NullPointerException.
Moreover, the code also used a FileWriter, which uses the platform default encoding, which might not be valid for JSON, and which might not be able to encode some of the characters. The encoding is now set explicitly to UTF-8.

fix: avoid NPE when saving storage state

---

examples/pom.xml

Without this config maven fails to download `0.190.0-SNAPSHOT` version of Playwright.

fix: add snapshot repo to the examples project

---

playwright/src/test/java/com/microsoft/playwright/TestPageEventNetwork.java
playwright/src/test/java/com/microsoft/playwright/TestPageRoute.java
playwright/src/test/java/com/microsoft/playwright/TestWorkers.java

Removing some of the methods as per discussion in https://github.com/microsoft/playwright/pull/5315 We'll add them back in the future if need be.

tests: stop using waitFor* methods which will be removed

---

tools/api-generator/src/main/java/com/microsoft/playwright/tools/ApiGenerator.java

These methods now have language filter in .md files and it doesn't include java.

chore: remove custom signatures for non-java methods

---

playwright/src/main/java/com/microsoft/playwright/Accessibility.java
playwright/src/main/java/com/microsoft/playwright/Browser.java
playwright/src/main/java/com/microsoft/playwright/BrowserContext.java
playwright/src/main/java/com/microsoft/playwright/BrowserType.java
playwright/src/main/java/com/microsoft/playwright/Dialog.java
playwright/src/main/java/com/microsoft/playwright/Download.java
playwright/src/main/java/com/microsoft/playwright/ElementHandle.java
playwright/src/main/java/com/microsoft/playwright/FileChooser.java
playwright/src/main/java/com/microsoft/playwright/Frame.java
playwright/src/main/java/com/microsoft/playwright/JSHandle.java
playwright/src/main/java/com/microsoft/playwright/Keyboard.java
playwright/src/main/java/com/microsoft/playwright/Mouse.java
playwright/src/main/java/com/microsoft/playwright/Page.java
playwright/src/main/java/com/microsoft/playwright/Playwright.java
playwright/src/main/java/com/microsoft/playwright/Request.java
playwright/src/main/java/com/microsoft/playwright/Route.java
playwright/src/main/java/com/microsoft/playwright/Selectors.java
playwright/src/main/java/com/microsoft/playwright/TimeoutError.java
playwright/src/main/java/com/microsoft/playwright/Video.java
playwright/src/main/java/com/microsoft/playwright/Worker.java
tools/api-generator/src/main/java/com/microsoft/playwright/tools/ApiGenerator.java

* Javadocs are now formatted from parsed md structures.
* Lists are properly formatted.
* Java snippets are preserved in javadocs.

docs: add code snippets from upstream

---

driver-bundle/src/main/java/com/microsoft/playwright/impl/DriverJar.java

When used with spring-boot-maven-plugin 'jar' file system's relative path resolution works in a way that
'/driver/mac/playwright.sh' relative to '/driver/mac/' is '../mac/playwright.sh' (see discussion in the bug and https://github.com/microsoft/playwright-java/issues/306#issuecomment-789665424 in particular). To work around that we convert to the default fs paths and do relative path resolution there.
Fixes #306

fix: use default file system for relative path resolution

---

Dockerfile.focal

* Copy browser dependencies from upstream [dockerfile](https://github.com/microsoft/playwright/blob/master/utils/docker/Dockerfile.focal)
* In addition to caching playwright maven modules also install browsers into local cache
* Set browser cache directory to /ms-playwright so that it is shared between users
* Intall latest LTS version of JDK - 11 instead of 14
#270

feat(docker): download browsers to local cache

---

.github/workflows/publish_canary_docker.yml
.github/workflows/publish_docker_release.yml

The comment which I've removed was obsolete, we used it in the past but then decided to not use this CLI argument anymore.
See here for reference of the upstream format, with this PR its then in sync.
https://github.com/microsoft/playwright/blob/master/.github/workflows/publish_release.yml#L76

devops: adjust pushed Docker tags to be consistent with pw

---

driver-bundle/pom.xml
driver-bundle/src/main/java/com/microsoft/playwright/impl/DriverJar.java
driver-bundle/src/test/java/com/microsoft/playwright/TestInstall.java
driver/pom.xml
driver/src/main/java/com/microsoft/playwright/impl/StreamRedirectThread.java
playwright/src/main/java/com/microsoft/playwright/impl/PipeTransport.java
playwright/src/main/java/com/microsoft/playwright/impl/PlaywrightImpl.java

* Spawn a new dedicated thread to pump stderr/stdout from the driver child process to playwright process to mitigate possible problems with inheriting streams in Java Enterprise described in #418
* Close driver connection when reading from child process fails, this should help with  #347

fix: manually pipe messages from child process sdtout/stderr

---

playwright/src/main/java/com/microsoft/playwright/impl/BrowserContextImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/Serialization.java
playwright/src/main/java/com/microsoft/playwright/impl/Utils.java

* Use `new ArrayList<>` instead of Collections.emptyList() which is implemented as a private class
* Use custom serializer for `Optional` class to avoid access to its private field
* Use custom serializer for `Path` class to avoid access to its implementation which private to JDK
Fixes #423

fix: avoid private field/class access from Gson

---

playwright/src/test/java/com/microsoft/playwright/TestChromiumTracing.java

Should fix the following error:
```
Error:  Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 16.072 s <<< FAILURE! - in com.microsoft.playwright.TestChromiumTracing
Error:  com.microsoft.playwright.TestChromiumTracing.shouldRunWithCustomCategoriesIfProvided(Path)  Time elapsed: 3.322 s  <<< ERROR!
java.io.IOException: Failed to delete temp directory C:\Users\RUNNER~1\AppData\Local\Temp\junit5012661792671279287. The following paths could not be deleted (see suppressed exceptions for details): , trace.json
```

test: close file reader when done

---

playwright/src/test/java/com/microsoft/playwright/TestScreencast.java

Should fix the following error:
```
Error:  Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.422 s <<< FAILURE! - in com.microsoft.playwright.TestScreencast
Error:  com.microsoft.playwright.TestScreencast.saveAsShouldThrowWhenNoVideoFrames(Path)  Time elapsed: 0.178 s  <<< ERROR!
java.io.IOException: Failed to delete temp directory C:\Users\RUNNER~1\AppData\Local\Temp\junit1703193493649673137. The following paths could not be deleted (see suppressed exceptions for details): , 9feae69455fef23b318030549c789932.webm
```

test(screencast): close context with video before returning from test

---

playwright/src/test/java/com/microsoft/playwright/TestNetworkRequest.java

```
Error:  Failures: 
Error:    TestNetworkRequest.shouldGetTheSameHeadersAsTheServer:118 expected: <{sec-fetch-mode=navigate, sec-fetch-site=none, upgrade-insecure-requests=1, host=localhost:9102, connection=keep-alive, sec-fetch-user=?1, accept-encoding=gzip, deflate, br, user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/92.0.4500.0 Safari/537.36, sec-fetch-dest=document, accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9}> but was: <{upgrade-insecure-requests=1, user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/92.0.4500.0 Safari/537.36}>
```
https://github.com/microsoft/playwright/issues/6690

test: disable test that flakes in Chromium

---

driver-bundle/src/main/java/com/microsoft/playwright/impl/DriverJar.java
driver-bundle/src/test/java/com/microsoft/playwright/TestInstall.java
driver/src/main/java/com/microsoft/playwright/impl/Driver.java
playwright/src/main/java/com/microsoft/playwright/CLI.java
playwright/src/main/java/com/microsoft/playwright/Playwright.java
playwright/src/main/java/com/microsoft/playwright/impl/PlaywrightImpl.java
playwright/src/test/java/com/microsoft/playwright/TestBase.java
playwright/src/test/java/com/microsoft/playwright/TestBrowserTypeConnect.java
playwright/src/test/java/com/microsoft/playwright/TestPlaywrightCreate.java
tools/api-generator/src/main/java/com/microsoft/playwright/tools/ApiGenerator.java

feat: accept driver env in Playwright.create()

---

jbang-catalog.json
scripts/playwright.java

current docs explains how when you have a maven project you can run the cli.
with this PR you can just use jbang.
if you don't have jbang installed already see jbang.dev/downloads or just run this first:
```
curl -Ls https://sh.jbang.dev | bash -s - app setup
```
then you can do:
```
jbang playwright@microsoft/playwright-java codegen -o Example.java
```
for now you can try it with the following which runs it from my branch:
```
jbang playwright@maxandersen/playwright-java/jbang codegen -o Example.java
```
I also opened https://github.com/microsoft/playwright/pull/7696 which adds small header to generated java code 
that enables you to run the generated scripts directly. if that happens you can just do `jbang Example.java` 
Thank you

feat: provide jbang-catalog to run playwright cli

---

playwright/src/main/java/com/microsoft/playwright/impl/Stream.java
playwright/src/test/java/com/microsoft/playwright/TestDownload.java

Otherwise java.io.InputStream.readAllBytes may throw as described in the bug (it first calls read with size=8192 and then with size=0 which we treated as read all remaining data).
Fixes #538

fix: support 0 size read from stream

---

playwright/src/test/java/com/microsoft/playwright/TestDownload.java

test: navigate to download url

---

README.md

Hi, I found that there has been a latest package (version 1.14.1) in the maven central repository, but it's still the old version number in the `README.md`, I think it should be updated, am I right ?

docs: update maven version number for README.md

---

playwright/src/main/java/com/microsoft/playwright/impl/RouteImpl.java
playwright/src/test/java/com/microsoft/playwright/TestRequestContinue.java

When there are many pages sending lots of requests it route handler may end up being called recursively and even cause stack overflow like in the linked issue. At the same time there is no good reason to block on `Route.continue/abort/fulfill` calls waiting for an ack from the driver. The network interception error (if any) should be surfaced on the Page object anyway.
#678

fix(route): do not wait for driver ack

---

driver-bundle/pom.xml
pom.xml
tools/test-local-installation/pom.xml

Looks like this option causes some of the tests (TestBrowserContextRoute and TestPageRoute) to hang. It was first noticed in Docker after https://github.com/microsoft/playwright-java/pull/657 but the tests also fail intermittently on Chromium Linux bot:

fix(tests): do not use redirectTestOutputToFile

---

scripts/update_readme.sh

Otherwise previous driver may be used which would result in incorrect browser versions.

devops: clean old build before updating readme

---

assertions/src/main/java/com/microsoft/playwright/impl/LocatorAssertionsImpl.java
assertions/src/main/java/com/microsoft/playwright/impl/PageAssertionsImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/APIRequestContextImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/BrowserImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/ElementHandleImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/FileChooserImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/FrameImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/LocatorImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/MouseImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/PageImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/Utils.java

Use reflection to convert between option types like `Page.ClickOptions` => `Frame.ClickOptions`. The converter does only shallow copy so it doesn't suffer from cyclic references. Also it shouldn't look into internal fields of JDK classes which could trigger errors like https://github.com/microsoft/playwright-java/issues/423

chore: convert using reflection instead of Gson

---

scripts/download_driver_for_all_platforms.sh

Since Nov 16, 2021, we have the following conventions:
- Drivers published from tip-of-tree have an `-alpha` version and are
stored at `/next` subfolder on Azure Storage.
- Drivers auto-published for each commit of the release branch have a `-beta` version and are
stored at `/next` subfolder on Azure Storage.
- Drivers published due to a release might have `-rc` as part of the
version, and are stored in root subfolder on Azure Storage.
We no longer have driver versions that include "next" as part of the
version. I kept it for backwards compatibility.

chore: proper driver URL detection

---

driver-bundle/src/main/java/com/microsoft/playwright/impl/DriverJar.java
driver-bundle/src/test/java/com/microsoft/playwright/TestInstall.java
driver/src/main/java/com/microsoft/playwright/impl/Driver.java

Allow specifying custom temp directory for extracting driver binaries when running playwright. As requested in the bug it can now be provided as `-D playwright.driver.tmpdir=/path/to/somewhere`
Fixes #728

feat: custom temp dir for driver via playwright.driver.tmpdir property

---

playwright/src/main/java/com/microsoft/playwright/impl/Connection.java

2aef5c674214c274f192206c9e408ac1463e2d57

cherry-pick(1.18): hide internal call from inspector log (#783)

---

.github/workflows/publish.yml

Thats how it is in Python, Node.js, vscode extension etc.

devops: trigger Java publish workflow on release

---

driver-bundle/src/test/java/com/microsoft/playwright/TestInstall.java
driver/src/main/java/com/microsoft/playwright/impl/Driver.java

This patch adds a logic to enable the loading of an alternative driver which can be set via the system property 'playwright.driver.impl'. If the property is not set, the default driver implementation will be loaded.
Fixes #856.

fix: enable loading alternative driver via system properties

---

playwright/src/main/java/com/microsoft/playwright/impl/TracingImpl.java
playwright/src/test/java/com/microsoft/playwright/TestTracing.java

Prior to this commit using `new Tracing.StartOptions().setSources(false) was
was wrongfully treated as `.setSources(true)` since it only tested the `Boolean` to be non-null.
Also, `includeSources` was converted into a local variable as it is not used anywhere else.

fix(tracing): support explicit StartOptions().setSources(false)

---

CONTRIBUTING.md
driver-bundle/src/main/java/com/microsoft/playwright/impl/DriverJar.java
scripts/download_driver_for_all_platforms.sh

This reverts commit 7eddd2d2b2ee1230381c095ebdaa1148218aa15d.
Reverting this change as we are going to branch for the next release and amr support
* is not covert by tests yet
* inclreases the size of the driver bundle which we'll likely want to fix before
release.
References https://github.com/microsoft/playwright-java/issues/836

Revert "Add Linux/arm64 support (#883)"

---

utils/docker/publish_docker.sh

Release Docker publish currently fails:
```
Run ./utils/docker/publish_docker.sh stable
ERROR: cannot publish stable docker with Playwright version ''
Error: Process completed with exit code 1.
```

fix: get docker version from pom.xml

---

CONTRIBUTING.md
driver-bundle/src/main/java/com/microsoft/playwright/impl/DriverJar.java
scripts/download_driver_for_all_platforms.sh

This reverts commit 536af6b3d8cd403e685cb0381b40010a8812fc8e.
Now that we cut 1.21 branch let's re-add support for arm linux and figure out how to do test infra for it.
#836

Revert "Revert "Add Linux/arm64 support (#883)" (#892)"

---

driver-bundle/src/test/java/com/microsoft/playwright/TestInstall.java

The test is failing on the bots, especially [on windows](https://github.com/microsoft/playwright-java/runs/6266381222?check_suite_focus=true):
```
Error:  Failures: 
Error:    TestInstall.shouldThrowWhenBrowserPathIsInvalid:52 Expected java.lang.RuntimeException to be thrown, but nothing was thrown.
```
#853

test: unflake TestInstall.shouldThrowWhenBrowserPathIsInvalid

---

examples/src/main/java/org/example/SelectorsAndKeyboardManipulation.java

I've noticed that in the examples, there weren't any showcases on how to use selectors and keyboard manipulation, so I've created one.
One of the main things that makes Playwright "Playwright" and just a web scraper is keyboard manipulation. One of the main things that Playwright can do that other web scrapers can't, is click on different selectors and manipulate the keyboard into accessing certain pages. 
I've made a simple example of how Playwright works with selectors. This example is quite simple. All it does is just go to "https://playwright.dev/java/", searches up "getting started" clicks on the First Script button, and takes a screenshot once new page loads.

Added Selectors and Keyboard Manipulation Example

---

.gitattributes

This should fix TestHar failures on Windows.

fix: use same eol setting in gitattributes as upstream

---

.github/workflows/test.yml
driver-bundle/src/test/java/com/microsoft/playwright/TestInstall.java

The test was failing in Docker and flaky on other bots (apparently because the browsers were already downloaded). Instead of running it in "isolation" just use reflection to temporarily clear singleton instance reference field.

chore: remove isolated tests

---

driver-bundle/src/main/java/com/microsoft/playwright/impl/driver/jar/DriverJar.java
driver-bundle/src/test/java/com/microsoft/playwright/TestInstall.java
driver/src/main/java/com/microsoft/playwright/impl/driver/Driver.java
driver/src/main/java/com/microsoft/playwright/impl/driver/DriverLogging.java
playwright/src/main/java/com/microsoft/playwright/CLI.java
playwright/src/main/java/com/microsoft/playwright/impl/PlaywrightImpl.java
playwright/src/test/java/com/microsoft/playwright/TestBrowserTypeConnect.java
playwright/src/test/java/com/microsoft/playwright/TestPageRequestFallback.java

Java 9 module system doesn't allow split packages (i.e. when same package is defined in more than one module). This PR makes each Playwright Maven module define unique package names. Only implementation (driver) packages are affected.
Fixes #996

fix: no split packages for compatibility with modules

---

playwright/src/main/java/com/microsoft/playwright/impl/VideoImpl.java
playwright/src/test/java/com/microsoft/playwright/TestScreencast.java

Copy python logic from https://github.com/microsoft/playwright-python/pull/1474

fix: prevent video.saveAs() from hanging

---

playwright/src/test/java/com/microsoft/playwright/TestBase.java
playwright/src/test/java/com/microsoft/playwright/TestBrowserContextAddCookies.java

an example failure: (see https://github.com/microsoft/playwright-java/runs/8146887116?check_suite_focus=true#step:7:345 )
Failures: 
Error:    TestBrowserContextAddCookies.shouldRoundtripCookie:62 expected: <[{"name":"username","value":"John Doe","domain":"localhost","path":"/","expires":1.696635616179373E9,"httpOnly":false,"secure":false,"sameSite":"LAX"}]> but was: <[{"name":"username","value":"John Doe","domain":"localhost","path":"/","expires":1.69663561617426E9,"httpOnly":false,"secure":false,"sameSite":"LAX"}]>
notice the `expires` property is different by a fraction.
in https://github.com/microsoft/playwright/blob/c58bfd0552da433cf69cc3ed8eadd1041e75a364/tests/library/browsercontext-cookies.spec.ts#L43-L73 this property is tested seperately

tests: unflake TestBrowserContextAddCookies.shouldRoundtripCookie

---

playwright/src/test/java/com/microsoft/playwright/TestBrowserContextAddCookies.java
playwright/src/test/java/com/microsoft/playwright/TestBrowserContextCookies.java
playwright/src/test/java/com/microsoft/playwright/Utils.java

follow up on #1045
remove duplicate test `TestBrowserContextAddCookies.shouldRoundtripCookie` of `TestBrowserContextCookies.shouldGetANonSessionCookie`
the original test is `browsercontext-cookies.spec.ts` - `should get a non-session cookie`
Maybe we should annotate the test-classes and test methods with the `@DisplayName` similar to how the `playwright-dotnet` repo does?

tests: remove duplicate cookies test

---

playwright/src/main/java/com/microsoft/playwright/impl/Serialization.java
playwright/src/test/java/com/microsoft/playwright/TestPageEvaluate.java

Since LocalDateTime is "cannot represent an instant on the time-line without additional information such as an offset or time-zone." we use system default time zone to serialize its value to protocol. All parsed timestamps are still represented as Date.
Fixes https://github.com/microsoft/playwright-java/issues/1044

fix: serialize LocalDateTime parameters as Date

---

driver-bundle/src/test/java/com/microsoft/playwright/impl/driver/jar/TestInstall.java

Fixes the following [errors](https://github.com/microsoft/playwright-java/runs/8254577880?check_suite_focus=true) in Docker:
```
[ERROR] Failures: 
[ERROR]   TestInstall.playwrightDriverAlternativeImpl:117 Expected java.lang.RuntimeException to be thrown, but nothing was thrown.
[ERROR]   TestInstall.shouldThrowWhenBrowserPathIsInvalid:81 Expected java.lang.RuntimeException to be thrown, but nothing was thrown.
```

test: make installation tests pass in docker

---

utils/docker/Dockerfile.focal

Playwright itself is still compiled with JDK 8 to ensure it runs on JDK 8+ but there is no reason not to use latest available JDK version in the Docker.
Fixes https://github.com/microsoft/playwright-java/issues/1050

feat(docker): bump jdk version to 17

---

utils/docker/Dockerfile.focal

Fixes https://github.com/microsoft/playwright-java/issues/1103

feat(docker): set JAVA_HOME to openjdk 17

---

playwright/src/main/java/com/microsoft/playwright/impl/LocatorImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/LocatorUtils.java
playwright/src/test/java/com/microsoft/playwright/TestSelectorsText.java

https://github.com/microsoft/playwright-java/issues/1101

fix: use internal:text* selectors

---

playwright/src/main/java/com/microsoft/playwright/impl/ArtifactImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/BrowserContextImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/BrowserImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/BrowserTypeImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/Connection.java
playwright/src/main/java/com/microsoft/playwright/impl/PageImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/TracingImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/Utils.java
playwright/src/main/java/com/microsoft/playwright/impl/VideoImpl.java
playwright/src/test/java/com/microsoft/playwright/TestDefaultBrowserContext2.java

Fixes https://github.com/microsoft/playwright-java/issues/1111

fix: NPE in setInputFiles

---

playwright/src/main/java/com/microsoft/playwright/impl/StackTraceCollector.java

Fixes https://github.com/microsoft/playwright-java/issues/1115

fix: do not fail on a bad file name in stack trace

---

playwright/src/main/java/com/microsoft/playwright/impl/LocatorImpl.java
playwright/src/test/java/com/microsoft/playwright/TestSelectorsGetBy.java

Fixes https://github.com/microsoft/playwright-java/issues/1130

cherry-pick(#1131): fix: implement LocatorImpl.getByRole

---

playwright/src/main/java/com/microsoft/playwright/impl/BrowserContextImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/PageImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/RouteImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/Router.java
playwright/src/test/java/com/microsoft/playwright/TestPageRoute.java

Allow to handle Route asynchronously. If a route handler matches but doesn't call any methods synchronously we assume it will handle the route later and stop iterating through other handlers in the list. If `fallback()` is called asynchronously it is equivalent to calling `resume()`.
Fixes https://github.com/microsoft/playwright-java/issues/1136

fix: asynchronous route handling

---

utils/docker/Dockerfile.focal

Fixes the following error:
```sh
Adding user `pwuser' ...
Adding new group `pwuser' (1000) ...
Adding new user `pwuser' (1000) with group `pwuser' ...
Creating home directory `/home/pwuser' ...
Copying files from `/etc/skel' ...
New password: Password change aborted.
passwd: Authentication token manipulation error
passwd: password unchanged
Use of uninitialized value $answer in chop at /usr/sbin/adduser line 591.
Use of uninitialized value $answer in pattern match (m//) at /usr/sbin/adduser line 592.
Try again? [y/N] Changing the user information for pwuser
Enter the new value, or press ENTER for the default
Full Name []: 	Room Number []: 	Work Phone []: 	Home Phone []: 	Other []: Use of uninitialized value $answer in chop at /usr/sbin/adduser line 621.
Use of uninitialized value $answer …
```

fix(docker): adduser error

---

driver-bundle/pom.xml
driver/pom.xml
playwright/pom.xml
pom.xml

devops: Improve plugin configuration inheritance usage.
- removing duplication of plugin definition in modules
- using single location to define all (parent)
- defined all used plugins via pluginManagement with
most recent versions.
- removed life cycle binding from pluginManagement
- moved life cycle binding to default location
- using jar-no-fork of maven-source-plugin.

devops: Improve plugin configuration inheritance usage (#1201)

---

driver-bundle/src/main/java/com/microsoft/playwright/impl/driver/jar/DriverJar.java
scripts/download_driver_for_all_platforms.sh

Fixes https://github.com/microsoft/playwright-java/issues/1198, https://github.com/microsoft/playwright-java/issues/1254

feat: bundle arm64 node binary for Apple Silicon

---

.github/workflows/test_docker.yml
utils/docker/Dockerfile.jammy
utils/docker/build.sh
utils/docker/publish_docker.sh

Fixes https://github.com/microsoft/playwright-java/issues/1191
Relates https://github.com/microsoft/playwright-python/issues/1858#issuecomment-1505185228

devops: publish Jammy Docker images

---

playwright/src/test/java/com/microsoft/playwright/TestBrowserContextCredentials.java
playwright/src/test/java/com/microsoft/playwright/TestBrowserContextFetch.java
playwright/src/test/java/com/microsoft/playwright/TestGlobalFetch.java
playwright/src/test/java/com/microsoft/playwright/Utils.java

Verify that the httpCredentials are not sent when origin mismatches (scheme or hostname or port different). See https://github.com/microsoft/playwright/pull/20374
It works on my side with roll of driver version 1.33.0-alpha-mar-28-2023 (I did not push the actual roll, I'll let you guys do it since other implementation may also need tests).

test: Restrain sending http credentials on a specific origin (for roll 1.33 driver)

---

utils/docker/publish_docker.sh

https://github.com/microsoft/playwright-java/actions/runs/4865569740/jobs/8676042256#step:6:27234
It broke but the damage seems to not be worth a new release.

devops(docker): fix Docker publishing

---

README.md
examples/src/main/java/org/example/PageScreenshot.java
examples/src/main/java/org/example/WebKitScreenshot.java

Currently, the documentation uses `http://whatsmyuseragent.org/` which is now a dead link filled with ads
It should instead be consistant and use the Playwright homepage

Updated dead links to use Playwright homepage in documentation

---

playwright/src/main/java/com/microsoft/playwright/Browser.java
playwright/src/main/java/com/microsoft/playwright/BrowserContext.java
playwright/src/main/java/com/microsoft/playwright/CDPSession.java
playwright/src/main/java/com/microsoft/playwright/JSHandle.java
playwright/src/main/java/com/microsoft/playwright/impl/BrowserContextImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/BrowserImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/CDPSessionImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/Connection.java
playwright/src/test/java/com/microsoft/playwright/TestBrowser.java
playwright/src/test/java/com/microsoft/playwright/TestBrowserContextCDPSession.java
tools/api-generator/src/main/java/com/microsoft/playwright/tools/ApiGenerator.java

Add new methods `BrowserContext.newCDPSession` and `Browser.newBrowserCDPSession` to create a [Chrome DevTools Protocol](https://chromedevtools.github.io/devtools-protocol/) session for the page and browser respectively.
Note that I just ported most of the code and tests from [playwright-dotnet](https://github.com/microsoft/playwright-dotnet)
Fixes #823

feat: Add support for Chrome DevTools Protocol (CDPSession)

---

pom.xml

Generates metadata for method parameters. Useful for inspecting method parameters via reflection.
Fixed #1368.
`javap` output before change:
```
public void startTracing(com.microsoft.playwright.Page, com.microsoft.playwright.Browser$StartTracingOptions);
descriptor: (Lcom/microsoft/playwright/Page;Lcom/microsoft/playwright/Browser$StartTracingOptions;)V
flags: (0x0001) ACC_PUBLIC
Code:
stack=5, locals=3, args_size=3
0: aload_0
1: ldc_w         #377                // String Browser.startTracing
4: aload_0
5: aload_1
6: aload_2
7: invokedynamic #379,  0            // InvokeDynamic #3:run:(Lcom/microsoft/playwright/impl/BrowserImpl;Lcom/microsoft/playwright/Page;Lcom/microsoft/playwright/Browser$StartTracingOptions;)Ljava/lang/Runnable;
12: invokevirtual #52                 // Method …
```

chore: Generate metadata for method parameters

---

playwright/src/main/java/com/microsoft/playwright/impl/Protocol.java
playwright/src/main/java/com/microsoft/playwright/impl/Serialization.java
playwright/src/test/java/com/microsoft/playwright/TestPageEvaluate.java

Upstream PR: https://github.com/microsoft/playwright/pull/26730
Reference: https://github.com/microsoft/playwright-java/issues/1353

chore: support js Map, Set in protocol results

---

playwright/src/test/java/com/microsoft/playwright/TestBrowserContextProxy.java

Fixes the following errors:
```
Error: 8 [ERROR] com.microsoft.playwright.TestBrowserContextProxy.shouldExcludePatterns  Time elapsed: 0.706 s  <<< ERROR!
com.microsoft.playwright.PlaywrightException: 
Error {
message='Navigation to "http://3.non.existent.domain.for.the.test/target.html" is interrupted by another navigation to "http://foo.is.the.another.test/target.html"
=========================== logs ===========================
navigating to "http://3.non.existent.domain.for.the.test/target.html", waiting until "load"
============================================================
name='Error
stack='Error: Navigation to "http://3.non.existent.domain.for.the.test/target.html" is interrupted by another navigation to "http://foo.is.the.another.test/target.html"
=========================== …
```

chore: unflake TestBrowserContextProxy.shouldExcludePatterns

---

playwright/src/main/java/com/microsoft/playwright/impl/LocalUtils.java
playwright/src/main/java/com/microsoft/playwright/impl/PlaywrightImpl.java
playwright/src/main/java/com/microsoft/playwright/junit/Options.java
playwright/src/main/java/com/microsoft/playwright/junit/impl/BrowserContextExtension.java
playwright/src/main/java/com/microsoft/playwright/junit/impl/BrowserExtension.java
playwright/src/main/java/com/microsoft/playwright/junit/impl/DeviceDescriptor.java
playwright/src/test/java/com/microsoft/playwright/TestPlaywrightDeviceOption.java

Reference https://github.com/microsoft/playwright-java/issues/939

feat: support device name in playwright fixtures

---

playwright/src/test/java/com/microsoft/playwright/TestPlaywrightCustomOptionFixtures.java

Motivation: There is no Google Chrome for `linux-arm64`.
Relates https://github.com/microsoft/playwright-browsers/pull/872.

test: do not rely on channel: chrome

---

playwright/src/test/java/com/microsoft/playwright/TestPlaywrightCurtomFixturesChannel.java
playwright/src/test/java/com/microsoft/playwright/TestPlaywrightCustomFixturesChannel.java

The test only runs when `BROWSER_CHANNEL` env variable is provided.
Fixes https://github.com/microsoft/playwright-java/issues/1478

test(junit): restore browser channel test

---

playwright/src/main/java/com/microsoft/playwright/impl/Connection.java
playwright/src/main/java/com/microsoft/playwright/impl/FrameImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/FrameLocatorImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/LocatorImpl.java
playwright/src/main/java/com/microsoft/playwright/impl/LocatorUtils.java
playwright/src/main/java/com/microsoft/playwright/impl/SharedSelectors.java
playwright/src/main/java/com/microsoft/playwright/junit/Options.java
playwright/src/test/java/com/microsoft/playwright/TestSelectorsGetBy.java

chore: custom test id per playwright instance

---

playwright/src/main/java/com/microsoft/playwright/junit/impl/PlaywrightExtension.java
playwright/src/test/java/com/microsoft/playwright/junit/ServerLifecycle.java
playwright/src/test/java/com/microsoft/playwright/junit/TestFixtureChannelOption.java
playwright/src/test/java/com/microsoft/playwright/junit/TestFixtureDeviceOption.java

This PR adds the ability to close Playwright objects after the entire test run.  I also added a `ParameterResolver` for server so we don't have to create methods to access it from the `serverMap`.
Ref: https://github.com/microsoft/playwright-java/issues/1369#issuecomment-1924579887

feat(junit): Close Playwright after test run

---

playwright/src/main/java/com/microsoft/playwright/junit/UsePlaywright.java
playwright/src/main/java/com/microsoft/playwright/junit/impl/ExtensionUtils.java
playwright/src/test/java/com/microsoft/playwright/junit/FixtureAbstractClass.java
playwright/src/test/java/com/microsoft/playwright/junit/TestFixtureWithBaseClass.java
playwright/src/test/java/com/microsoft/playwright/junit/TestFixturesWithNestedClass.java

Resolves #1514 
Allows fixtures to be used inside nested class and allows inheriting fixtures from base classes.

fix(junit): Fixes fixtures not working in nested junit test classes

---

playwright/pom.xml
pom.xml

Javadoc options generated by the plugin have changed to include `-source 8`:
```
$ diff good.txt bad.txt 
5a6,7
> -source
> '8'
24a27,28
> 'https://docs.oracle.com/javase/8/docs/api' '/Users/yurys/playwright-java/playwright/target/javadoc-bundle-options'
> -linkoffline
```
The options are from the following:
```
Command line was: /Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home/bin/javadoc @options
Refer to the generated Javadoc files in '/Users/<user>/playwright-java/playwright/target/site/apidocs' dir.
```
Turns out `-source '8'` triggers an assertion in the javadoc tool, so for now we just pass `11` as the source version. Our sources are compiled with java 8 compatibility mode, so it shouldn't make any difference in the generated docs.
Reference …

fix(docs): generate javadocs

---

.azure-pipelines/publish.yml

And were actually not produced in the recent release https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9394315&view=logs&j=c5c5d0ad-9fc4-5fcb-d69d-7db2ecc16a23&t=bbccc425-c27d-5062-b951-856f97a85174

devops: stop producing .sha256 files, they are not required anymore

---

.github/workflows/test.yml

The tests have been failing recently on macOS:

devops: install msedge on macosx

---

README.md

In Mobile and geolocation demo, code `page.click("a[data-original-title=\"Show My Location\"]")` will cause error while running.Because the website already change the attribute.

fix: Update README.md to fix wrong demo code

---

driver-bundle/src/main/java/com/microsoft/playwright/impl/driver/jar/DriverJar.java

Replaces System.out.println with logMessage in DriverJar so as to only print out log messages if the driver is in debug mode.

fix: Replaced println with logMessage in DriverJar

---

.github/dependabot.yml

Otherwise it generates one PR per patch update which is too much noise.
See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups

devops(dependabot): update all deps in single PR monthly

---

playwright/src/test/java/com/microsoft/playwright/TestBrowserContextFetch.java
playwright/src/test/java/com/microsoft/playwright/TestBrowserContextProxy.java
playwright/src/test/java/com/microsoft/playwright/TestClientCertificates.java

Similar to https://github.com/microsoft/playwright/pull/31724.
The test-failures are unrelated.

test: remove per-context proxy hacks for Windows/Chromium

---

playwright/src/test/java/com/microsoft/playwright/HttpsConfiguratorImpl.java
playwright/src/test/java/com/microsoft/playwright/ServerWithClientCertificate.java
playwright/src/test/java/com/microsoft/playwright/TestClientCertificates.java
playwright/src/test/java/com/microsoft/playwright/TestPageInterception.java
playwright/src/test/java/com/microsoft/playwright/TestPlaywrightCreate.java

The problem before was that the Java WebServer was configured in a way, that when no client certificates were passed during the TLS handshake, it was closing the connection / aborting the handshake immediately. This meant for us that we were closing the Socks connections which triggered `is interrupted by another navigation` or `EMPTY_RESPONSE`. Also this lead to differences to the tests compared to upstream and failing tests across the board.
This PR aligns it with upstream and fixed the tests.

test: fix client-certificate tests

---

playwright/src/test/java/com/microsoft/playwright/TestPageClock.java

Fixes the following error on the bots:
```
Error:    TestPageClock.shouldNotRunTimeBeforePopupOnPause:313 » Playwright Error {
message='ReferenceError: time is not defined
at eval (eval at evaluate (:234:30), <anonymous>:1:1)
at eval (<anonymous>)
at UtilityScript.evaluate (<anonymous>:234:30)
at UtilityScript.<anonymous> (<anonymous>:1:44)
name='Error
stack='Error: ReferenceError: time is not defined
at eval (eval at evaluate (:234:30), <anonymous>:1:1)
at eval (<anonymous>)
at UtilityScript.evaluate (<anonymous>:234:30)
at UtilityScript.<anonymous> (<anonymous>:1:44)
at CRExecutionContext.evaluateWithArguments (/tmp/playwright-java-947970650740572645/package/lib/server/chromium/crExecutionContext.js:79:33)
at async LongStandingScope._race …
```

test: unflake TestPageClock

---

playwright/src/main/java/com/microsoft/playwright/impl/WaitableRace.java
playwright/src/test/java/com/microsoft/playwright/TestBrowserContextBasic.java

Previously it would fail with this exception:
```
java.lang.AssertionError
at com.microsoft.playwright.impl.WaitableRace.get(WaitableRace.java:40)
at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:132)
at com.microsoft.playwright.impl.BrowserContextImpl.waitForCondition(BrowserContextImpl.java:670)
at com.microsoft.playwright.BrowserContext.waitForCondition(BrowserContext.java:1545)
```

fix: waitForCondition should not call predicate after it returned true

---

playwright/src/main/java/com/microsoft/playwright/impl/UrlMatcher.java
playwright/src/main/java/com/microsoft/playwright/impl/Utils.java
playwright/src/test/java/com/microsoft/playwright/TestPageRoute.java

Extracted from https://github.com/microsoft/playwright-java/pull/1717. There should be no behaviour changes.
This moves `rawSource` towards having it lazily determined which matching source it is - this helps us to align with upstream.

chore: refactor UrlMatcher

---

playwright/src/main/java/com/microsoft/playwright/impl/ClockImpl.java
playwright/src/test/java/com/microsoft/playwright/TestTracing.java

Due to the lack of the proper wrapping calls, all `Clock` APIs were not being logged into the recorded trace.
* Trace entries are now properly created
* `Clock` entries are named `Clock.*` matching JS, rather than the previously existing `BrowserContext.clock*`

fix(tracing): Properly log Clock calls

---

playwright/src/main/java/com/microsoft/playwright/impl/UrlMatcher.java
playwright/src/test/java/com/microsoft/playwright/TestRouteWebSocket.java

Note: `URL` is not able to parse a `ws://` url, only `URI` is able to.
This applies [this](https://github.com/microsoft/playwright/blob/4819747c85faa8cad0f33d770e1e63f6fb894d49/packages/playwright-core/src/utils/isomorphic/urlMatch.ts#L101-L103) upstream logic to Java.
Relates https://github.com/microsoft/playwright-java/issues/1715
Extracted from https://github.com/microsoft/playwright-java/pull/1717

fix(webSocketRoute): resolve URL against baseURL

---

playwright/src/main/java/com/microsoft/playwright/impl/UrlMatcher.java
playwright/src/test/java/com/microsoft/playwright/TestRouteWebSocket.java

Fixes https://github.com/microsoft/playwright-java/pull/1717
Fixes https://github.com/microsoft/playwright-java/issues/1715
This ports the following upstream change: https://github.com/microsoft/playwright/blob/bc1a8c21912cf82f60d584438cd94c24f9daf8a4/packages/playwright-core/src/utils/isomorphic/urlMatch.ts#L110

fix(urlMatcher): normalize URLs to align with Node.js parser behavior

---

.devcontainer/devcontainer.json
.github/dependabot.yml

Otherwise it defaults to 'https://github.com/devcontainers/images/tree/main/src/universal' which is Ubuntu 20.04.

devops: add DevContainer config

---

playwright/pom.xml
pom.xml

Extracted from https://github.com/microsoft/playwright-java/pull/1761.

test: fix  'SLF4J(W): No SLF4J providers were found.' warning

---

playwright/src/test/java/com/microsoft/playwright/Server.java
playwright/src/test/java/com/microsoft/playwright/TestBrowserContextCredentials.java
playwright/src/test/java/com/microsoft/playwright/TestGlobalFetch.java

Extracted from https://github.com/microsoft/playwright-java/pull/1761.
This fixes:
```
WARNING: sendResponseHeaders: being invoked with a content length for a HEAD request
```

test: do not send Content-Length header for HEAD requests

---

.azure-pipelines/publish.yml

We still have [the check](https://github.com/microsoft/playwright-java/blob/01c72ac5d30908016c3a308a1afa445f77e5082b/.azure-pipelines/publish.yml#L31-L34) that the job runs on a `release-*` branch, hopefully it passes and provides extra guarantee that we only publish from release branches..

devops: trigger publish on new tag

---

.azure-pipelines/publish.yml

Bash doesn't support [[ ... =~ ... ]] with double backslashes for escaping . in regex the same way Zsh does.
- `\.` is sufficient in Bash (not `\\.`).
- The double backslash `\\.` is interpreted literally as `\.` in the regex, which doesn’t behave as intended in Bash.
Fixes the following error:
```
Starting: Check the branch is a release branch
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.250.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
========================== Starting Command Output …
```

devops: fix release branch name check

---

playwright/src/test/java/com/microsoft/playwright/TestChromiumTracing.java

Same as https://github.com/microsoft/playwright/pull/36612

chore: unflake tracing test

---

CONTRIBUTING.md
pom.xml

Previously they were filtering by project `playwright` which e.g. not included rebuilding the driver. This reverts what was added in https://github.com/microsoft/playwright-java/pull/1484 and adds the ignore flag.

chore: fix Maven test commands
